### ISSUE TITLE
Make use of local images

### ISSUE THREAD

**Issue by ClaytonSiby** [vanheaven-ui/apple-clone#1]
For reliability, please do make use of local files and folders. In your project you have different background images that you're referencing direct from the server, which is not reliable as it will reduce the performance of your site.

*Solution* -> download the images and save them in a local folder in your machine and reference them for the background images, that way you can increase your site efficiency.

**Comment by vanheaven-ui** [comment]
Thanks @ClaytonSiby,  this has been amended.
